/// Reserve - File heavily edited by PR: Mapping editor.
/// See https://github.com/space-wizards/space-station-14/pull/34302
/// https://github.com/Monolith-Station/Monolith/pull/3810
/// and https://github.com/Reserve-Station/Reserve-Station/pull/82 for more details.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingVisibilityWindow : DefaultWindow
{
    public MappingVisibilityWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

