- type: job
  id: JobMarshallCCTC
  name: job-name-cctc-marshall
  description: job-description-cctc-marshall
  playTimeTracker: JobMarshallCCTC
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hrs - 100 > 50 - mono
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 18000 # 5 hrs as security guard - mono
    # Factions are required here because Overseer needs to actually understand how both factions work.
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
  whitelisted: false
  startingGear: MarshallCCTCGear
  alwaysUseSpawner: true
  assignedCompany: CCTC
  icon: "JobIconCCTCMarshall" # Mono
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 50 # Second from top
  canBeAntag: false
  accessGroups:
  - CCTC
  access:
  - Maintenance
  - External
  - Service
  - Frontier
  - Mercenary
  special:
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: cctc-marshall
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Mono - remove TSFMC implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      #- type: NpcFactionMember - Commented out to seperate them from TSFMC.
      #  factions:
      #  - TSFMC
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: MarshallCCTCGear
  equipment:
    pocket1: WeaponPistolCCTCGalactica
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
    - EncryptionKeyCentCom
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - ShipVoucherFrontierGuard
    - PhoneInstrumentHigh
    - CCHandheldOverwatchConsole
