- type: job
  id: JobShareholderCCTC
  name: job-name-cctc-shareholder
  description: job-description-cctc-shareholder
  playTimeTracker: JobShareholderCCTC
  startingGear: ShareholderCCTCGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hrs - 100 > 50 - mono
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 18000 # 5 hrs as security guard - mono
    - !type:RoleTimeRequirement
      role: JobServiceWorker
      time: 18000 # 5 hrs
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 54000 # 15 hours
  canBeAntag: false
  icon: "JobIconCCTCNoble"
  assignedCompany: CCTC
  supervisors: job-supervisors-sr
  weight: 160
  displayWeight: 60 # Top
  setPreference: true
  accessGroups:
  - CCTC
  access:
  - Service
  - Maintenance
  - External
  - Frontier
  - StationTrafficController
  special:
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: cc-stc
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: ShareholderCCTCGear
  #equipment:
  #  id: StcPDA
  storage:
    back:
    - Flash
    - RubberStampStc
    - EncryptionKeyStationMaster
    - PhoneInstrumentHigh
