- type: job
  id: JobServiceTechCCTC
  name: job-name-cctc-servicetech
  description: job-description-cctc-servicetech
  playTimeTracker: JobServiceTechCCTC
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 # three hours
  startingGear: ServiceTechCCTCGear
  alwaysUseSpawner: true
  icon: "JobIconCCTCServiceTech"
  supervisors: job-supervisors-sr
  weight: 60 # Frontier
  displayWeight: 10 # Frontier
  assignedCompany: CCTC
  canBeAntag: false
  access:
  - Maintenance
  - External # Frontier
  - Service
  - Frontier # Frontier
  - Mercenary
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: ServiceTechCCTCGear
  equipment:
    id: CCServiceWorkerPDA
  storage:
    back:
    - EncryptionKeyService
